// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {config} from '../models';
import {storage} from '../models';

export function ExecuteTidy(arg1:Array<media.MoveRequest>,arg2:boolean):Promise<media.TidySummary>;

export function GetSettings():Promise<config.Settings>;

export function Greet(arg1:string):Promise<string>;

export function ListDuplicateGroups():Promise<Array<storage.DuplicateGroup>>;

export function ReloadSettings():Promise<config.Settings>;

export function RunScan():Promise<media.Summary>;
