// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteTidy(arg1, arg2) {
  return window['go']['main']['App']['ExecuteTidy'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDuplicateGroups() {
  return window['go']['main']['App']['ListDuplicateGroups']();
}

export function ReloadSettings() {
  return window['go']['main']['App']['ReloadSettings']();
}

export function RunScan() {
  return window['go']['main']['App']['RunScan']();
}
